services:
  asynq-app:
    build:
      context: .
      dockerfile: Dockerfile.asynq
    image: asynq-${APP_ENV:-dev}-app:${SERVICE_ASYNQ_VERSION:-latest}
    container_name: asynq-${APP_ENV:-dev}-app
    environment:
      - TZ=${TZ:-UTC}
    ports:
      - ${SERVICE_ASYNQ_PORT:-8081}:8081
    volumes:
      - ./storage:/app/storage
      - ./config.asynq.yaml:/app/config.yaml:ro
    restart: unless-stopped
    networks:
      - asynq_app

networks:
  asynq_app:
    name: asynq_${APP_ENV:-dev}_app_net
    external: true