services:
  asynq-app:
    build:
      context: .
      dockerfile: Dockerfile.asynq
    image: asynq-app:latest
    container_name: asynq-app
    ports:
      - 8080:8080
    volumes:
      - ./storage:/app/storage
      - ./config.asynq.yaml:/app/config.yaml
    restart: unless-stopped
    networks:
      - asynq_app_net

networks:
  asynq_app_net:
    name: asynq_app_net
    external: true