services:
  core-app:
    build:
      context: .
      dockerfile: Dockerfile.core
    image: core-app:latest
    container_name: core-app
    ports:
      - 8080:8080
    volumes:
      - ./storage:/app/storage
      - ./core.config.yaml:/app/config.yaml
    restart: unless-stopped
    networks:
      - core_app_net

networks:
  core_app_net:
    name: core_app_net
    external: true