app:
  env: "dev"
  name: "example-app"
  domain: "http://localhost"
  timezone: "Asia/Jakarta"
server:
  asynq:
    host: "0.0.0.0"
    port: 8081
    address: "0.0.0.0:8081"
    additional:
      asynq.route.monitoring: /asynqmon
      asynq.log.level: '2' # Debug: 1 | Info: 2 | Warn: 3 | Error: 4 | Fatal: 5
  http:
    host: "0.0.0.0"
    port: 8080
    address: "0.0.0.0:8080"
smtp:
  gmail:
    host: localhost
    port: 587
    credential:
      name: "Admin Example"
      email: admin.example.local
      username: "example"
      password: "example"
template:
  example.email.template: "./storage/template/my_template.tpl" 
log:
  debug: # For logging debug app
    disabled: false
    console:
      disabled: false
      level: -1 # Trace: -1 | Debug: 0 | Info: 1 | Warn: 2 | Error: 3 | Fatal: 4 | Panic: 5
    file:
      disabled: false
      level: 1 # Trace: -1 | Debug: 0 | Info: 1 | Warn: 2 | Error: 3 | Fatal: 4 | Panic: 5
      rotation:
        basePath: "./storage/logs/core/debug" # where you need store to store log and what a log name
        filename: "app_core_debug_process.log" # what a log name
        maxBackup: 10 # how much backup files
        maxSize: 100 # how much maximum megabytes
        maxAge: 0 # how much maximum days, default is 0 that means not deleted old logs
        localTime: false # default UTC | false
        compress: false # default false
  io: # For logging api input-output / IO proccess
    disabled: false
    console:
      disabled: false
      level: -1 # Trace: -1 | Debug: 0 | Info: 1 | Warn: 2 | Error: 3 | Fatal: 4 | Panic: 5
    file:
      disabled: false
      level: 1 # Trace: -1 | Debug: 0 | Info: 1 | Warn: 2 | Error: 3 | Fatal: 4 | Panic: 5
      rotation:
        basePath: "./storage/logs/core/io" # where you need store to store log and what a log name
        filename: "app_core_api_io_process.log" #  what a log name
        maxBackup: 10 # how much backup files
        maxSize: 100 # how much maximum megabytes
        maxAge: 0 # how much maximum days, default is 0 that means not deleted old logs
        localTime: false # default UTC | false
        compress: false # default false
  trx: # For logging Transaction process your client
    disabled: false
    console:
      disabled: false
      level: 0 # Trace: -1 | Debug: 0 | Info: 1 | Warn: 2 | Error: 3 | Fatal: 4 | Panic: 5
    file:
      disabled: false
      level: 0 # Trace: -1 | Debug: 0 | Info: 1 | Warn: 2 | Error: 3 | Fatal: 4 | Panic: 5
      rotation:
        basePath: "./storage/logs/core/trx/{CLIENT}" # where you need store to store log and what a log name and {CLIENT} will be replaced by client key
        filename: "app_core_api_for_{CLIENT}_trx_process.log" # what a log name and {CLIENT} will be replaced by client key
        maxBackup: 10 # how much backup files
        maxSize: 100 # how much maximum megabytes
        maxAge: 0 # how much maximum days, default is 0 that means not deleted old logs
        localTime: false # default UTC | false
        compress: false # default false
cache:
  redis:
    disabled: false
    dbname: "0"
    port: 6379
    address: "localhost"
    credential:
      enabled: true
      username: "default"
      password: ""
db:
  postgres:
    disabled: false
    driver: "postgres"
    dbname: "example-db"
    port: 5432
    address: "localhost"
    credential:
      enabled: true
      username: "postgres"
      password: "example"
    options:
      timezone: "Asia/Jakarta"
      sslmode: "disable"
      connectionTimeout: 30