app:
  env: "dev"
  name: "example-app"
  domain: "localhost"

http:
  address: "127.0.0.1:8080"

log:
  enabledConsole: true
  enabledFile: true
  level: 0 # Trace: -1 | Debug: 0 | Info: 1 | Warn: 2 | Error: 3 | Fatal: 4 | Panic: 5
  rotation:
    pathFile: "./storage/logs/core/app_core.log" # where you need store to store log and what a log name
    maxBackup: 10 # how much backup files
    maxSize: 100 # how much maximum megabytes
    maxAge: 0 # how much maximum days, default is 0 that means not deleted old logs
    localTime: false # default UTC | false
    compress: false # default false

cache:
  enabled: true
  dbname: "0"
  port: 6379
  address: "localhost"
  credential:
    enabled: true
    username: "default"
    password: ""

db:
  enabled: true
  dbname: "example-db"
  port: 5432
  address: "localhost"
  credential:
    enabled: true
    username: "postgres"
    password: "QwErTy2025"
  options:
    timezone: "Asia/Jakarta"
    sslmode: "disable"
    connectionTimeout: 30